[package]
name = "pairing"

# Remember to change version string in README.md.
version = "0.18.0"
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Jack Grigg <jack@z.cash>",
]
readme = "README.md"
license = "MIT/Apache-2.0"

description = "Pairing-friendly elliptic curve library"
documentation = "https://docs.rs/pairing/"
homepage = "https://github.com/zkcrypto/pairing"
repository = "https://github.com/zkcrypto/pairing"
edition ="2018"

[dependencies]
ff = { version = "0.8", default-features = false }
group = { version = "0.8", default-features = false }

[dev-dependencies]
rand_core = "0.5"
rand_xorshift = "0.2"

[badges]
maintenance = { status = "actively-developed" }
